name: Build Test CI
on:
  pull_request:
jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use Node.js 14
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
