name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use Node.js 14
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup
        run: npm i -g @antfu/ni
      - name: Install Dependencies
        run: nci
      - name: Build
        run: nr build
